# Jeu de données : questions étiquetées par intention
# 4 catégories : emploi_du_temps, cours, orientation, faq

donnees = [
    # --- EMPLOI DU TEMPS ---
    ("Quel est mon prochain cours ?", "emploi_du_temps"),
    ("Quels cours ai-je vendredi ?", "emploi_du_temps"),
    ("Où a lieu le cours de M. Karray demain ?", "emploi_du_temps"),
    ("À quelle heure commence mon cours de réseaux ?", "emploi_du_temps"),
    ("Dans quelle salle est le TP de systèmes ?", "emploi_du_temps"),
    ("Quel est mon emploi du temps de la semaine ?", "emploi_du_temps"),
    ("Ai-je cours lundi matin ?", "emploi_du_temps"),
    ("Quand est mon prochain TD ?", "emploi_du_temps"),
    ("Quels sont mes horaires aujourd'hui ?", "emploi_du_temps"),
    ("À quelle heure finit le cours de base de données ?", "emploi_du_temps"),
    ("Quelle salle pour le cours de génie logiciel ?", "emploi_du_temps"),
    ("Mon planning de jeudi ?", "emploi_du_temps"),

    # --- COURS ---
    ("Résume le cours de base de données", "cours"),
    ("Quels sont les prérequis du cours de réseaux ?", "cours"),
    ("Où trouver le TP de la semaine 3 en algorithmique ?", "cours"),
    ("De quoi parle le module de génie logiciel ?", "cours"),
    ("Quel est le contenu du cours de systèmes d'exploitation ?", "cours"),
    ("Explique le cours de programmation web", "cours"),
    ("Qui enseigne le module de réseaux ?", "cours"),
    ("Quels sont les chapitres du cours d'algorithmique ?", "cours"),
    ("Donne-moi le syllabus de base de données", "cours"),
    ("Quels sujets sont abordés en systèmes d'exploitation ?", "cours"),
    ("Résume le module de développement web", "cours"),
    ("Quels sont les objectifs du cours de génie logiciel ?", "cours"),
    ("Quels sont les objectifs du cours de Anglais Technique ?", "cours"),
    ("Quels sont les objectifs du cours de Français ?", "cours"),
    ("De quoi parle le module de Français ?", "cours"),
    ("Qui enseigne le cours de Français ?", "cours"),


    # --- ORIENTATION ---
    ("Quelles filières choisir si j'aime les mathématiques ?", "orientation"),
    ("Quels débouchés après une licence en informatique ?", "orientation"),
    ("Vers quel master m'orienter ?", "orientation"),
    ("Quelle spécialité choisir en informatique ?", "orientation"),
    ("Quels métiers après ce diplôme ?", "orientation"),
    ("Je suis intéressé par l'IA, quelle filière ?", "orientation"),
    ("Quelles études pour devenir développeur ?", "orientation"),
    ("Conseille-moi une orientation professionnelle", "orientation"),
    ("Quels parcours sont possibles après le S6 ?", "orientation"),
    ("Quelle voie choisir si j'aime les réseaux ?", "orientation"),

    # --- FAQ ---
    ("Comment s'inscrire à la bibliothèque ?", "faq"),
    ("Quelle est la date limite pour les bourses ?", "faq"),
    ("Où se trouve le service de scolarité ?", "faq"),
    ("Comment obtenir un certificat de scolarité ?", "faq"),
    ("Quand ont lieu les examens ?", "faq"),
    ("Comment justifier une absence ?", "faq"),
    ("Comment accéder au wifi du campus ?", "faq"),
    ("Comment m'inscrire aux examens ?", "faq"),
    ("Où récupérer ma carte étudiante ?", "faq"),
    ("Quels sont les horaires de la scolarité ?", "faq"),
    ("Comment contacter l'administration ?", "faq"),
    ("Où déposer un dossier de bourse ?", "faq"),
    # --- Exemples supplémentaires EMPLOI DU TEMPS ---
    ("C'est quoi mon planning de demain ?", "emploi_du_temps"),
    ("Montre-moi mes séances de la semaine", "emploi_du_temps"),
    ("Quel cours j'ai après la pause ?", "emploi_du_temps"),
    ("À quelle heure est mon TP de mercredi ?", "emploi_du_temps"),
    ("Est-ce que j'ai cours cet après-midi ?", "emploi_du_temps"),
    ("Quelle est la salle de mon prochain TD ?", "emploi_du_temps"),
    ("Mes horaires de cours de la journée ?", "emploi_du_temps"),

    # --- Exemples supplémentaires COURS ---
    ("Fais-moi un résumé du module réseaux", "cours"),
    ("Quel est le programme du cours d'algo ?", "cours"),
    ("Décris le contenu du cours de BD", "cours"),
    ("Liste les notions du cours de SE", "cours"),
    ("Quelles compétences dans le module web ?", "cours"),
    ("Parle-moi du cours de génie logiciel", "cours"),
    ("Quel support pour le cours de réseaux ?", "cours"),

    # --- Exemples supplémentaires ORIENTATION ---
    ("Quel master après l'informatique ?", "orientation"),
    ("Je veux travailler dans la cybersécurité, quelle voie ?", "orientation"),
    ("Quelles carrières avec ce diplôme ?", "orientation"),
    ("Aide-moi à choisir ma spécialisation", "orientation"),
    ("Quel parcours pour devenir data scientist ?", "orientation"),
    ("Vers quoi m'orienter après la licence ?", "orientation"),
    ("Quels secteurs recrutent en informatique ?", "orientation"),

    # --- Exemples supplémentaires FAQ ---
    ("Comment réserver une salle de travail ?", "faq"),
    ("Quels documents pour l'inscription ?", "faq"),
    ("Où est le bureau des bourses ?", "faq"),
    ("Comment payer mes frais de scolarité ?", "faq"),
    ("Quand sortent les résultats d'examens ?", "faq"),
    ("Comment changer de groupe ?", "faq"),
    ("Où trouver le règlement intérieur ?", "faq"),
    # --- Vague 2 : EMPLOI DU TEMPS ---
    ("Quel cours commence à 8h30 ?", "emploi_du_temps"),
    ("Je veux voir mon agenda de la semaine", "emploi_du_temps"),
    ("Y a-t-il cours samedi ?", "emploi_du_temps"),
    ("Quelle matière en première heure demain ?", "emploi_du_temps"),
    ("Mes cours du matin ?", "emploi_du_temps"),
    ("Quand se termine ma journée de cours ?", "emploi_du_temps"),
    ("Le TP de jeudi est dans quelle salle ?", "emploi_du_temps"),
    ("Combien de cours ai-je aujourd'hui ?", "emploi_du_temps"),
    ("À quelle heure mon cours de l'après-midi ?", "emploi_du_temps"),
    ("Mon planning du week-end ?", "emploi_du_temps"),

    # --- Vague 2 : COURS ---
    ("Quelles sont les parties du cours de réseaux ?", "cours"),
    ("Donne le détail du module algorithmique", "cours"),
    ("Quel est le plan du cours de base de données ?", "cours"),
    ("Sur quoi porte le module de systèmes ?", "cours"),
    ("Explique-moi le contenu du génie logiciel", "cours"),
    ("Quelles technologies dans le cours web ?", "cours"),
    ("Quel est l'objectif du module réseaux ?", "cours"),
    ("Liste les thèmes du cours d'algo", "cours"),
    ("Quelles méthodes sont vues en génie logiciel ?", "cours"),
    ("Présente le cours de programmation web", "cours"),

    # --- Vague 2 : ORIENTATION ---
    ("Quelle filière pour aimer le code ?", "orientation"),
    ("Quels métiers en développement web ?", "orientation"),
    ("Je veux faire de la recherche, quel parcours ?", "orientation"),
    ("Quelle spécialité pour travailler en entreprise ?", "orientation"),
    ("Vers quel domaine me diriger ?", "orientation"),
    ("Quelles options après ma licence ?", "orientation"),
    ("Quel diplôme pour devenir ingénieur logiciel ?", "orientation"),
    ("Que faire après mes études d'informatique ?", "orientation"),
    ("Quels débouchés dans l'intelligence artificielle ?", "orientation"),
    ("Aide-moi à planifier ma carrière", "orientation"),

    # --- Vague 2 : FAQ (renforcée) ---
    ("Comment emprunter un livre à la bibliothèque ?", "faq"),
    ("Quel est le montant des frais d'inscription ?", "faq"),
    ("Où puis-je imprimer des documents sur le campus ?", "faq"),
    ("Comment demander une attestation de réussite ?", "faq"),
    ("Quelles sont les dates des vacances universitaires ?", "faq"),
    ("Comment m'inscrire en deuxième année ?", "faq"),
    ("Où se trouve le restaurant universitaire ?", "faq"),
    ("Comment contacter mon responsable de filière ?", "faq"),
    ("Quels sont les horaires d'ouverture de la bibliothèque ?", "faq"),
    ("Comment obtenir mon relevé de notes ?", "faq"),
    ("Quelle est la procédure pour une réinscription ?", "faq"),
    ("Où déposer une réclamation de note ?", "faq"),
    ("Comment activer mon compte étudiant ?", "faq"),
    ("Quels documents pour la carte de transport ?", "faq"),
]